name: Generate ASCII Workflow
on: push
jobs:
  generate_ascii_job: 
    runs-on: ubuntu-latest
    
    steps:
    - name: checkout repository
      uses: actions/checkout@v4

    - name: welcome Generate Ascii workflow
      run: echo welcome Generate Ascii workflow

    - name: Install cowsay program
      run: sudo apt-get install cowsay -y

    - name: Execute cowsay command
      run: cowsay -f dragon "Run for a cover. I am dragon" >> dragon.txt

    - name: Test file exists
      run: |
           ls -lart
           grep -i "dragon" dragon.txt

    - name: Run file
      run: cat dragon.txt