name: Matrix config
on: 
  workflow_dispatch:
jobs:
  deploy: 
    strategy:
      #prevents github cancelling all in progress jobs if any matrix job fails. Default -true
      fail-fast: false
      #maximum number of jobs can run simultaneously when using a  matrix job strategy
      max-parallel: 2
      matrix:
        os: [ubuntu-latest,ubuntu-20.04,windows-latest]
        images: [hello-world, alpine]
        exclude: 
          - images: alpine
            os: windows-latest
        include: 
          - images: amd64/alpine
            os: ubuntu-20.04
  
    #runs this job in all the above mentioned OS and run all the images
    # windows do not support alpine images. so we could add additional configuration to bypass using exclude option
    # "include" option to include certain only on specific os
    runs-on: ${{matrix.os}}
    steps:
    - name: Echo Docker Details
      run: docker info
    - name: Run Images on ${{matrix.os}}
      run: docker run ${{matrix.images}}
